// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package grpc.greet;

public interface ComplexCallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.greet.ComplexCall)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string intro = 2;</code>
   * @return The intro.
   */
  java.lang.String getIntro();
  /**
   * <code>string intro = 2;</code>
   * @return The bytes for intro.
   */
  com.google.protobuf.ByteString
      getIntroBytes();

  /**
   * <code>string closing = 3;</code>
   * @return The closing.
   */
  java.lang.String getClosing();
  /**
   * <code>string closing = 3;</code>
   * @return The bytes for closing.
   */
  com.google.protobuf.ByteString
      getClosingBytes();
}
