// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package grpc.greet;

public final class GreetProto {
  private GreetProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_greet_SimpleCall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_greet_SimpleCall_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_greet_Call_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_greet_Call_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_greet_ComplexCall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_greet_ComplexCall_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_greet_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_greet_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013greet.proto\022\ngrpc.greet\"\032\n\nSimpleCall\022" +
      "\014\n\004name\030\001 \001(\t\"&\n\004Call\022\014\n\004name\030\001 \001(\t\022\020\n\010l" +
      "anguage\030\002 \001(\t\";\n\013ComplexCall\022\014\n\004name\030\001 \001" +
      "(\t\022\r\n\005intro\030\002 \001(\t\022\017\n\007closing\030\003 \001(\t\"\030\n\005Re" +
      "ply\022\017\n\007message\030\001 \001(\t2\273\001\n\014GreetService\0226\n" +
      "\007CallOne\022\026.grpc.greet.SimpleCall\032\021.grpc." +
      "greet.Reply\"\000\0223\n\010CallMany\022\020.grpc.greet.C" +
      "all\032\021.grpc.greet.Reply\"\0000\001\022>\n\016CallDiplom" +
      "atic\022\027.grpc.greet.ComplexCall\032\021.grpc.gre" +
      "et.Reply\"\000B \n\ngrpc.greetB\nGreetProtoP\001\242\002" +
      "\003GRTb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_greet_SimpleCall_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_greet_SimpleCall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_greet_SimpleCall_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_grpc_greet_Call_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_greet_Call_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_greet_Call_descriptor,
        new java.lang.String[] { "Name", "Language", });
    internal_static_grpc_greet_ComplexCall_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_greet_ComplexCall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_greet_ComplexCall_descriptor,
        new java.lang.String[] { "Name", "Intro", "Closing", });
    internal_static_grpc_greet_Reply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_greet_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_greet_Reply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
